# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Docker jobs

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  javabuild:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name : Check Java version
      run: java -version
    - name: MAven version check
      run: mvn -version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
 
  dockerimage:

    runs-on: ubuntu-latest
    needs: javabuild
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app
        
    - name: Logging into docker
      run: docker login ghcr.io -u attilaszegedi -p ${{ github.token }}

    - name: Build docker
      run: docker build . -t ghcr.io/attilaszegedi/cubix/1/homework/app:springboot

    - name: Publish docker
      run: docker push ghcr.io/attilaszegedi/cubix/1/homework/app:springboot
      


